
const MOCK_GENRES = [
  { id: 28, name: 'Action' }, { id: 12, name: 'Adventure' },
  { id: 35, name: 'Comedy' }, { id: 18, name: 'Drama' },
  { id: 27, name: 'Horror' }, { id: 878, name: 'Science Fiction' },
  { id: 53, name: 'Thriller' }, { id: 10749, name: 'Romance' },
]

const MOCK_DIRECTOR = { job: 'Director', name: 'Christopher Nolan', profile_path: null }
const MOCK_TRAILER  = { type: 'Trailer', site: 'YouTube', key: 'YoHD9XEInc0' }
const MOCK_CAST = Array.from({ length: 10 }, (_, i) => ({
  id: i, name: ['Leonardo DiCaprio','Scarlett Johansson','Tom Hanks','Meryl Streep','Denzel Washington','Cate Blanchett','Brad Pitt','Natalie Portman','Morgan Freeman','Emma Stone'][i],
  character: `Character ${i + 1}`, profile_path: null,
}))

export const MOCK_MOVIES = [
  { id: 27205,  title: 'Inception',              vote_average: 8.8, release_date: '2010-07-16', poster_path: '/ljsZTbVsrQSqZgWeep2B1QiDKuh.jpg', backdrop_path: '/s3TBrRGB1iav7gFOCNx3H31MoES.jpg', overview: 'A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea.', genre_ids: [28, 878, 53], popularity: 120 },
  { id: 157336, title: 'Interstellar',            vote_average: 8.6, release_date: '2014-11-05', poster_path: '/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg', backdrop_path: '/xJHokMbljvjADYdit5fK5VQsXEG.jpg', overview: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.', genre_ids: [12, 18, 878], popularity: 115 },
  { id: 238,    title: 'The Godfather',           vote_average: 9.2, release_date: '1972-03-14', poster_path: '/3bhkrj58Vtu7enYsLe1rjPU8o97.jpg', backdrop_path: '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg', overview: 'The aging patriarch of an organized crime dynasty transfers control to his reluctant son.', genre_ids: [18, 80], popularity: 100 },
  { id: 155,    title: 'The Dark Knight',         vote_average: 9.0, release_date: '2008-07-18', poster_path: '/qJ2tW6WMUDux911r6m7haRef0WH.jpg', backdrop_path: '/hkBaDkMWbLaf8B1lsWsKX7Ew3Xq.jpg', overview: 'When the menace known as the Joker wreaks havoc on Gotham, Batman must confront one of the greatest psychological tests.', genre_ids: [28, 18, 53], popularity: 130 },
  { id: 680,    title: 'Pulp Fiction',            vote_average: 8.9, release_date: '1994-10-14', poster_path: '/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg', backdrop_path: '/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg', overview: 'The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in tales of violence and redemption.', genre_ids: [53, 80], popularity: 98 },
  { id: 13,     title: 'Forrest Gump',            vote_average: 8.8, release_date: '1994-07-06', poster_path: '/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg', backdrop_path: '/3h1JZGDhZ8nzxdgvkxha0qBqi05.jpg', overview: 'The presidencies of Kennedy and Johnson, the Vietnam War, and other events unfold through the perspective of an Alabama man.', genre_ids: [18, 35], popularity: 95 },
  { id: 11,     title: 'Star Wars: A New Hope',   vote_average: 8.6, release_date: '1977-05-25', poster_path: '/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg', backdrop_path: '/zqkmTXzjkAgXmEWLRsY4UpTWCeo.jpg', overview: 'Luke Skywalker joins forces with a Jedi Knight, a cocky pilot and two droids to save the galaxy from the Empire.', genre_ids: [12, 28, 878], popularity: 110 },
  { id: 122,    title: 'The Lord of the Rings: The Return of the King', vote_average: 9.0, release_date: '2003-12-17', poster_path: '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg', backdrop_path: '/lXhgCODAbBXL5buk9yEmTpOoOgR.jpg', overview: 'Gandalf and Aragorn lead the World of Men against Sauron\'s army to draw his gaze from Frodo and Sam as they approach Mount Doom.', genre_ids: [12, 28, 18], popularity: 108 },
  { id: 278,    title: 'The Shawshank Redemption',vote_average: 9.3, release_date: '1994-09-23', poster_path: '/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg', backdrop_path: '/avedvodAZUcwqevBfm8p4G2NziQ.jpg', overview: 'Two imprisoned men bond over years, finding solace and eventual redemption through acts of common decency.', genre_ids: [18], popularity: 92 },
  { id: 424,    title: "Schindler's List",        vote_average: 9.0, release_date: '1993-12-15', poster_path: '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg', backdrop_path: '/loRmRzQXZeqG78TqZuyvSlEQfZb.jpg', overview: 'In German-occupied Poland during World War II, industrialist Oskar Schindler saves his Jewish employees.', genre_ids: [18], popularity: 88 },
  { id: 550,    title: 'Fight Club',              vote_average: 8.8, release_date: '1999-10-15', poster_path: '/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg', backdrop_path: '/hZkgoQYus5vegHoetLkCJzb17zJ.jpg', overview: 'An insomniac office worker and a devil-may-care soap maker form an underground fight club.', genre_ids: [18, 53], popularity: 105 },
  { id: 19404,  title: 'Dilwale Dulhania Le Jayenge', vote_average: 8.7, release_date: '1995-10-20', poster_path: '/lfRkUr7DYdHldAw3T1XSdMd3VEj.jpg', backdrop_path: '/1HnSFtH8PQHH6PY3MlTGbJxWqFN.jpg', overview: 'When two NRIs fall in love during a trip to Europe, it\'s up to them to convince their traditional families.', genre_ids: [18, 10749, 35], popularity: 82 },
  { id: 372058, title: 'Your Name',               vote_average: 8.5, release_date: '2016-08-26', poster_path: '/q719jXXEzOoYaps6babgKnONONX.jpg', backdrop_path: '/mMtUybQ6hL24FXo0F3Z4j2KG7kZ.jpg', overview: 'Two strangers find themselves linked in a bizarre way. When a connection forms, will distance be the only thing to keep them apart?', genre_ids: [16, 18, 10749], popularity: 90 },
  { id: 346364, title: 'It',                      vote_average: 7.3, release_date: '2017-09-08', poster_path: '/9E2y5Q7WlCVNEhP5GkVCommistay.jpg', backdrop_path: '/mrjESAbsjL1lzSllFrjLouIgvhu.jpg', overview: 'A group of bullied kids band together when a shape-shifting monster, taking the appearance of a clown, begins hunting children.', genre_ids: [27, 53], popularity: 85 },
  { id: 299536, title: 'Avengers: Infinity War',  vote_average: 8.4, release_date: '2018-04-27', poster_path: '/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg', backdrop_path: '/bOGkgRGdhrBYJSLpXaxhXVstddV.jpg', overview: 'The Avengers and their allies must be willing to sacrifice all in an attempt to defeat Thanos before his blitz of devastation.', genre_ids: [12, 28, 878], popularity: 125 },
  { id: 324857, title: 'Spider-Man: Into the Spider-Verse', vote_average: 8.4, release_date: '2018-12-14', poster_path: '/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg', backdrop_path: '/67NTgBMxmEBOMeTIeBNBUEr2YPQS.jpg', overview: 'Teen Miles Morales becomes Spider-Man of his universe and must stop a threat to all realities.', genre_ids: [16, 12, 28], popularity: 97 },
  { id: 98,     title: 'Gladiator',               vote_average: 8.5, release_date: '2000-05-05', poster_path: '/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg', backdrop_path: '/6WBIzCgmDCYrqh64yDREGeDk9d3.jpg', overview: 'A former Roman general sets out to exact vengeance against the corrupt emperor who murdered his family.', genre_ids: [28, 12, 18], popularity: 93 },
  { id: 185,    title: 'Raiders of the Lost Ark', vote_average: 8.4, release_date: '1981-06-12', poster_path: '/ceG9VzoRAVGwivFU403Wc3AHRys.jpg', backdrop_path: '/4qCqAdHcNKeAHcK8tJ8wNJgNGLF.jpg', overview: 'Archaeologist and adventurer Indiana Jones is hired to find the Ark of the Covenant before the Nazis.', genre_ids: [12, 28], popularity: 88 },
  { id: 769,    title: 'GoodFellas',              vote_average: 8.7, release_date: '1990-09-19', poster_path: '/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg', backdrop_path: '/sw7mordbZxgITU877yTpZCud90M.jpg', overview: 'The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen.', genre_ids: [18, 80], popularity: 86 },
  { id: 389,    title: 'Léon: The Professional',  vote_average: 8.5, release_date: '1994-09-14', poster_path: '/yI6X2cCM5YPJtxMhUd3dPGqDAhw.jpg', backdrop_path: '/qPgVBQmRBi5DGvHGBbJ8R1RomCW.jpg', overview: 'Mathilda, a 12-year-old girl, is reluctantly taken in by Léon, a professional cleaner, after her family is murdered.', genre_ids: [28, 18, 53], popularity: 91 },
]